(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.

Parameter a: Prop.

Parameter b: Prop.

Parameter c: Prop.

(* Why3 goal *)
Theorem Thm01 : ((a \/ b) -> c) -> b -> c.
(* Why3 intros h1 h2. *)
Proof.
tauto. (*Preuve automatique*)
Qed.

Print Thm01.
