(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.

Parameter a: Prop.

Parameter b: Prop.

Parameter c: Prop.

Parameter e: Prop.

Parameter y: Prop.

Parameter r: Prop.

(* Why3 goal *)
Theorem Thm06 : ((e -> y \/ r) /\ (y -> r)) -> ~ r -> ~ e.
(* Why3 intros (h1,h2) h3. *)
Proof.
(*intros (h1,h2) h3.*)
tauto.

Qed.

Print Thm06.
