(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.

Parameter a: Prop.

Parameter b: Prop.

Parameter c: Prop.

(* Why3 goal *)
Theorem Thm02 : True.
Proof.
tauto.

Qed.

Print Thm02.
