(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.

Parameter a: Prop.

Parameter b: Prop.

Parameter c: Prop.

(* Why3 goal *)
Theorem Thm05 : (~ b -> ~ a) -> a -> b.
Proof.
tauto.

Qed.

Print Thm05.

